"""XT-Aegis: evidence-first deterministic controls around agent actions."""

from xt_aegis.backup import BackupManifest, create_backup, restore_backup, verify_backup
from xt_aegis.controller import (
    ControllerAttempt,
    ControllerBudgets,
    ControllerCheckEvidence,
    ControllerResult,
    ControllerRunContext,
    ControllerStopReason,
    DiagnoseRepairController,
    InfrastructureUnavailableError,
    ProviderAdmission,
)
from xt_aegis.controller_state import ControllerStateRecord, ControllerStateStore
from xt_aegis.models import (
    ActionRequest,
    CommandAction,
    CommandSpec,
    CompiledSkill,
    ExecutionReasonCode,
    ExecutionResult,
    ExecutionStatus,
    FileWriteAction,
    Provenance,
    RiskLevel,
    SkillContract,
)
from xt_aegis.notifications import (
    ApprovalNotifier,
    DecisionVerdict,
    PendingApproval,
    SignedDecision,
)
from xt_aegis.proposals import (
    FakeProposalProvider,
    Proposal,
    ProposalOutcome,
    ProposalProvider,
    ProposalRequest,
    ProposalStatus,
    ProviderProfile,
    ProviderUsage,
    RequestIdentitySource,
    SamplingProfile,
    SecureRequestIdentitySource,
    TrustedActionEnvelope,
    TrustedEnvelopeConfig,
    TrustedRequestIds,
    build_action_request,
)
from xt_aegis.runner import HarnessRunner
from xt_aegis.side_effects import (
    EffectIdentity,
    EffectRecord,
    EffectState,
    ProtectedEffectRunner,
)
from xt_aegis.skill import SkillCompiler
from xt_aegis.verification_models import BackendName, VerificationResult, VerificationStatus

__all__ = [
    "ActionRequest",
    "ApprovalNotifier",
    "BackendName",
    "BackupManifest",
    "CommandAction",
    "CommandSpec",
    "CompiledSkill",
    "ControllerAttempt",
    "ControllerBudgets",
    "ControllerCheckEvidence",
    "ControllerResult",
    "ControllerRunContext",
    "ControllerStateRecord",
    "ControllerStateStore",
    "ControllerStopReason",
    "DecisionVerdict",
    "DiagnoseRepairController",
    "EffectIdentity",
    "EffectRecord",
    "EffectState",
    "ExecutionReasonCode",
    "ExecutionResult",
    "ExecutionStatus",
    "FakeProposalProvider",
    "FileWriteAction",
    "HarnessRunner",
    "InfrastructureUnavailableError",
    "PendingApproval",
    "Proposal",
    "ProposalOutcome",
    "ProposalProvider",
    "ProposalRequest",
    "ProposalStatus",
    "ProtectedEffectRunner",
    "Provenance",
    "ProviderAdmission",
    "ProviderProfile",
    "ProviderUsage",
    "RequestIdentitySource",
    "RiskLevel",
    "SamplingProfile",
    "SecureRequestIdentitySource",
    "SignedDecision",
    "SkillCompiler",
    "SkillContract",
    "TrustedActionEnvelope",
    "TrustedEnvelopeConfig",
    "TrustedRequestIds",
    "VerificationResult",
    "VerificationStatus",
    "build_action_request",
    "create_backup",
    "restore_backup",
    "verify_backup",
]

__version__ = "0.2.0"
